### ISSUE TITLE
Sorting with local characters in library tabs

### ISSUE THREAD

**Issue by alesny** [eisnerd/mupeace#11]
Library tabs, like Composers or Works displays local characters correctly but they are not sorted correctly. If, for example, some composer starts with 'Č' (which is > 'C' but < 'D') it's displayed after 'Z' composers.
I guess that using java.text.Collator for sorting would solve this problem.

Anyway, thanks for this great app!

**Comment by alesny** [comment]
The sorting works now but the first characters shown on the right are not sorted correctly, see the screenshot: ![2015-02-16 16_42](https://cloud.githubusercontent.com/assets/10012376/6214913/7b0f23b4-b5fc-11e4-9d12-baf87015f955.png)

**Comment by eisnerd** [comment]
Curious. That doesn't match the order of the items in the list at all. I have no idea whether that can be fixed in the app code. It's a standard ListView.

**Comment by alesny** [comment]
It works in the way (it's not visible on the screenshot) that if you scroll without the slider, it's sorted correctly and if you scroll the list using the right slider, the first characters are not sorted correctly but it jumps on the list position according to the first character shown on the slider. So when I move the slider a little bit as it's shown on the screenshot, it jumps on the list position where are "S..." words.
